### ISSUE TITLE
Server crashes when starting without a data.json file

### ISSUE THREAD

**Issue by honmanyau** [freeCodeCamp/tools-dashboard#33]
There is currently no sample `data.json` in the `/dashboard-api` directory. Since there are multiple dependencies on the file within the directory, a server would simply crash. I think we need to provide a sample data at the very least so that anyone can spin up the local server.

As @RandellDawson mentioned, that solution is not ideal because one cannot test the most up-to-date data. We could potentially write the scripts to pull the most up-to-date from the production server once things are settled.

**Comment by RandellDawson** [comment]
I just added a `sample_data.json` which one can make a copy and name it `data.json` to have something.
